### ISSUE TITLE
Method length is too high #5

### ISSUE THREAD

**Issue by ernest-ns** [aniket-k-kaushik/sales-tax-calculator#11]
https://github.com/aniket-k-kaushik/sales-tax-calculator/issues/5 [Method length is too high](https://github.com/aniket-k-kaushik/sales-tax-calculator/issues/5)

Looks like you accidentally closed this issue ☝️.

**Comment by aniket-k-kaushik** [comment]
yes, My mistake, I was closing Issue #3 , test for the core logic.
